# Generated by Django 3.2 on 2021-04-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='removedDate',
            field=models.DateTimeField(null=True),
        ),
    ]
