# Generated by Django 3.2 on 2021-04-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
