# Generated by Django 3.2 on 2021-04-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Bucket',
            new_name='bucket',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='User',
            new_name='user',
        ),
    ]
