# Generated by Django 3.2 on 2021-04-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210411_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='userID',
            new_name='user',
        ),
    ]
