# Generated by Django 3.2 on 2021-04-12 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='transactionDate',
        ),
    ]
